import { Template } from '../types';

const Templates: {[index: string]: Template } = {
  discogs: {
    artist: '#profile_title a',
    title: '#profile_title > span:nth-child(2)',
    date: '.content:nth-child(9) > a',
    type: '.content:nth-child(5)',
    format: '.content:nth-child(5)',
    discSize: '.content:nth-child(5)',
    discSpeed: '.content:nth-child(5)',
    label: '.content:nth-child(3) > a:nth-child(1)',
    catalogId: '.content:nth-child(3)',
    countries: '.content:nth-child(7) > a',
    trackPositions: '.track .tracklist_track_pos',
    trackArtists: '',
    trackTitles: '.tracklist_track > .track > .tracklist_track_title',
    trackDurations: '.track .tracklist_track_duration > span',
  },
  bandcamp: {
    artist: 'h3 > span > a',
    title: '.trackTitle:nth-child(1)',
    date: '.tralbum-credits',
    type: '.buyItemPackageTitle',
    format: '.digitaldescription',
    discSize: '',
    discSpeed: '',
    label: '#band-name-location > .title',
    catalogId: '',
    countries: '.tralbum-tags',
    trackPositions: '.track_row_view .track_number',
    trackArtists: '.tracklist_track > .track > .tracklist_track_title',
    trackTitles: '.track_row_view .track-title',
    trackDurations: '.track_row_view .time',
  },
  boomkat: {
    artist: '.detail--artists > a',
    title: '.detail_album',
    date: '.product-note:nth-child(3)',
    type: '.product-review',
    format: '.active > a',
    discSize: '',
    discSpeed: '',
    label: '.label-placeholder',
    catalogId: '.catalogue-number-placeholder',
    countries: '',
    trackPositions: '.product-listing .table-row > .title',
    trackArtists: '',
    trackTitles: '.product-listing .table-row > .title',
    trackDurations: '.product-listing .table-row > .time',
  },
};

export default Templates;
